apiVersion: apps/v1
kind: Deployment
metadata:
  name: ente-museum
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ente-museum
  template:
    metadata:
      labels:
        app: ente-museum
    spec:
      serviceAccountName: ente-museum-sa
      containers:
        - name: museum
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
          volumeMounts:
            - mountPath: "/data"
              name: museum-storage
            - mountPath: "/configurations"
              subPath: "production.yaml"
              name: ente-config
      volumes:
        - name: museum-storage
          persistentVolumeClaim:
            claimName: ente-museum-pvc
        - name: ente-config
          secret:
            secretName: ente-config-secret