apiVersion: v1
kind: Secret
metadata:
  name: ente-config-secret
data:
  local.yaml: |
    log-file: ""
    apps:
        public-albums:
        cast:
        accounts:
        family:

    smtp:
        host:
        port:
        username:
        password:
        email:
        sender-name:

    transmail:
        key:

    apple:
        shared-secret:

    stripe:
        us:
            key:
            webhook-secret:
        in:
            key:
            webhook-secret:
        whitelisted-redirect-urls: []
        path:
            success: ?status=success&session_id={CHECKOUT_SESSION_ID}
            cancel: ?status=fail&reason=canceled

    webauthn:
        rpid: localhost
        rporigins:
            - "http://localhost:3001"

    discord:
        bot:
            cha-ching:
                token:
                channel:
            mona-lisa:
                token:
                channel:

    zoho:
        client-id:
        client-secret:
        refresh-token:
        list-key:
        topic-ids:

    listmonk:
        server-url:
        username:
        password:
        list-ids:

    internal:
        silent: false
        health-check-url:
        admins: []
        admin:
        disable-registration: false

    replication:
        enabled: false
        worker-url:
        worker-count: 6
        tmp-storage: tmp/replication

    jobs:
        cron:
            skip: false
        remove-unreported-objects:
            worker-count: 1
        clear-orphan-objects:
            enabled: false
            prefix: ""
  production.yaml: {{ .Values.ente.config | b64enc | quote }}