name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Build Helm chart
        run: helm package .

      - name: Create gh-pages branch
        run: |
          git config --global user.email "jatin.katyal13@gmail.com"
          git config --global user.name "Jatin Katyal"
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages

      - name: Publish Helm chart to GitHub Pages
        run: |
          mkdir -p docs
          mv *.tgz docs/
          helm repo index docs --url https://jatinkatyal13.github.io/ente-helm/
          git add docs/
          git commit -m "Publish Helm chart"
          git push origin gh-pages