name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Build Helm chart
        run: ls && helm package .

      - name: Publish Helm chart to GitHub Pages
        run: |
          git config --global user.email "jatin.katyal13@gmail.com"
          git config --global user.name "Jatin Katyal"
          git pull --rebase origin gh-pages
          git checkout gh-pages

          helm repo index . --url https://jatinkatyal13.github.io/ente-helm/

          git add . 
          git commit -m "Publish Helm chart"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jatinkatyal13/ente-helm.git gh-pages